# general settings
name: SDL_VFI
model_type: SDLModel
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CIT
    task: vfi
    type: CITDataset
    dataroot_cit: [datasets/VFI/adobe240fps/train, datasets/VFI/vimeo_triplet/train]
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: CIT
    task: vfi
    type: CITDataset
    dataroot_cit: [datasets/VFI/ucf101_triplet/validation]
    io_backend:
      type: disk

# network structures
network_g:
  type: SDLNet
  num_in_ch: 6
  num_out_ch: 3
  split: 0.5
  num_feat: 32
  nrow: 3
  ncol: 6


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000, 400000, 500000]
    gamma: 0.8

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  #pixel_opt:
  #  type: MSELoss
  #  loss_weight: 1.0
  #  reduction: mean

  charbonnier_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1.0  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 0.1
    style_weight: 0
    criterion: l1

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
